name: etl_sales_transaction
version: "1.0"
config-version: 2

profile: etl_sales_transaction

model-paths: ["models"]
macro-paths: ["macros"]

models:
  etl_sales_transaction:
    stg:
      +materialized: ephemeral
    int:
      +materialized: ephemeral
    mart:
      +materialized: table
      +tags: ["mart"]

vars:
  company: "{{ env_var('COMPANY') }}"
  department: "{{ env_var('DEPARTMENT') }}"
  account: "{{ env_var('ACCOUNT') }}"